######################################################################
#
# File name : pcreg_tb.udo
# Created on: Mon Oct 28 21:01:50 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
