######################################################################
#
# File name : pcreg_tb_wave.do
# Created on: Mon Oct 28 21:27:14 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
