######################################################################
#
# File name : alu_tb_wave.do
# Created on: Mon Nov 11 22:05:31 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
