######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Sun Sep 15 00:37:11 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
