######################################################################
#
# File name : tb_simulate.do
# Created on: Mon Oct 14 20:32:55 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.tb xil_defaultlib.glbl

do {tb_wave.do}

view wave
view structure
view signals

do {tb.udo}

run 1000ns
