######################################################################
#
# File name : tb_wave.do
# Created on: Mon Oct 14 20:32:55 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
