######################################################################
#
# File name : encoder_tb.udo
# Created on: Sat Oct 12 20:17:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
