######################################################################
#
# File name : encoder_tb_simulate.do
# Created on: Sat Oct 12 20:17:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.encoder_tb xil_defaultlib.glbl

do {encoder_tb_wave.do}

view wave
view structure
view signals

do {encoder_tb.udo}

run 1000ns
