######################################################################
#
# File name : ram2_tb_simulate.do
# Created on: Tue Nov 19 00:30:13 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.ram2_tb xil_defaultlib.glbl

do {ram2_tb_wave.do}

view wave
view structure
view signals

do {ram2_tb.udo}

run 1000ns
