######################################################################
#
# File name : ram2_tb.udo
# Created on: Tue Nov 19 00:16:54 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
