######################################################################
#
# File name : ram2_tb_wave.do
# Created on: Tue Nov 19 00:30:13 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
