######################################################################
#
# File name : ram_tb_wave.do
# Created on: Mon Nov 18 23:23:22 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
