######################################################################
#
# File name : FA_tb_wave.do
# Created on: Mon Oct 21 19:59:32 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
