######################################################################
#
# File name : DataCompare4_tb_wave.do
# Created on: Mon Oct 21 16:25:21 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
