######################################################################
#
# File name : DataCompare4_tb_simulate.do
# Created on: Mon Oct 21 16:25:21 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.DataCompare4_tb xil_defaultlib.glbl

do {DataCompare4_tb_wave.do}

view wave
view structure
view signals

do {DataCompare4_tb.udo}

run 1000ns
