######################################################################
#
# File name : extend_tb_wave.do
# Created on: Sun Sep 15 00:33:57 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
