set_property SRC_FILE_INFO {cfile:E:/shuziluojiwork/shiyan7_2/shiyan7_2.srcs/constrs_1/new/222.xdc rfile:../../../shiyan7_2.srcs/constrs_1/new/222.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports I_CLK]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports rst]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports O_CLK]
