######################################################################
#
# File name : JK_FF_tb_wave.do
# Created on: Mon Oct 28 19:43:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
