######################################################################
#
# File name : Divider_tb_simulate.do
# Created on: Mon Nov 04 22:40:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.Divider_tb xil_defaultlib.glbl

do {Divider_tb_wave.do}

view wave
view structure
view signals

do {Divider_tb.udo}

run 1000ns
