######################################################################
#
# File name : de_selector14_teb_wave.do
# Created on: Mon Sep 30 23:53:53 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
