######################################################################
#
# File name : de_selector14_teb_simulate.do
# Created on: Mon Sep 30 23:53:53 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.de_selector14_teb xil_defaultlib.glbl

do {de_selector14_teb_wave.do}

view wave
view structure
view signals

do {de_selector14_teb.udo}

run 1000ns
