######################################################################
#
# File name : encoder83_pti_tb.udo
# Created on: Sat Oct 12 20:52:16 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
