######################################################################
#
# File name : encoder83_pti_tb_compile.do
# Created on: Sat Oct 12 20:52:13 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modelsim_10.4c\\win32pe\\vlib work
E:\\modelsim_10.4c\\win32pe\\vlib msim

E:\\modelsim_10.4c\\win32pe\\vlib msim/xil_defaultlib

E:\\modelsim_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

E:\\modelsim_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../1012SHIYAN3_4.srcs/sources_1/new/encoder83_Pri.v" \
"../../../1012SHIYAN3_4.srcs/sim_1/new/encoder83_pti_tb.v" \


# compile glbl module
E:\\modelsim_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

