######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Sun Sep 15 00:38:58 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
