######################################################################
#
# File name : Asynchronous_D_FF_tb_wave.do
# Created on: Mon Oct 28 18:59:40 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
