######################################################################
#
# File name : Synchronous_D_FF_tb.udo
# Created on: Mon Oct 28 18:34:38 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
