######################################################################
#
# File name : selector41_tb_compile.do
# Created on: Tue Oct 01 11:54:39 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modelsim_10.4c\\win32pe\\vlib work
E:\\modelsim_10.4c\\win32pe\\vlib msim

E:\\modelsim_10.4c\\win32pe\\vlib msim/xil_defaultlib

E:\\modelsim_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

E:\\modelsim_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../9.30shiyan_2.srcs/sources_1/new/selector41.v" \
"../../../9.30shiyan_2.srcs/sim_1/new/test_930.v" \


# compile glbl module
E:\\modelsim_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

