######################################################################
#
# File name : selector41_tb_wave.do
# Created on: Tue Oct 01 11:54:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
