######################################################################
#
# File name : three_state_gates_tb_wave.do
# Created on: Sun Sep 15 21:17:05 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
