######################################################################
#
# File name : three_state_gates_tb.udo
# Created on: Sun Sep 15 00:44:21 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
