######################################################################
#
# File name : Adder_tb_compile.do
# Created on: Mon Oct 21 20:43:53 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modelsim_10.4c\\win32pe\\vlib work
E:\\modelsim_10.4c\\win32pe\\vlib msim

E:\\modelsim_10.4c\\win32pe\\vlib msim/xil_defaultlib

E:\\modelsim_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

E:\\modelsim_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../1021shiyan5_4.srcs/sources_1/new/Adder.v" \
"../../../1021shiyan5_4.srcs/sim_1/new/Adder_tb.v" \


# compile glbl module
E:\\modelsim_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

