######################################################################
#
# File name : Counter8_tb_simulate.do
# Created on: Sat Jan 04 02:26:34 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.Counter8_tb xil_defaultlib.glbl

do {Counter8_tb_wave.do}

view wave
view structure
view signals

do {Counter8_tb.udo}

run 1000ns
