######################################################################
#
# File name : Counter8_tb_wave.do
# Created on: Sat Jan 04 02:26:34 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
