######################################################################
#
# File name : Regfiles_tb_wave.do
# Created on: Tue Nov 19 12:44:56 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
